using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using Hashim.JourneyPoint.Domain.Domain.Enums;
using Hashim.JourneyPoint.Domain.Domain.Hires;
using Shesha.Domain.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Hashim.JourneyPoint.Domain.Domain.Wellness
{
    /// <summary>
    /// A scheduled wellness check-in for a hire during their onboarding journey.
    /// Generated at journey activation at milestone periods (Day30, Day60, Day90).
    /// The hire answers AI-generated questions; a summary is produced by Groq on submission
    /// for Facilitator review on the pipeline board.
    /// </summary>
    [Entity(TypeShortAlias = "JourneyPoint.WellnessCheckIn")]
    public class WellnessCheckIn : FullAuditedEntity<Guid>, IMustHaveTenant
    {
        /// <summary>Tenant ownership.</summary>
        public virtual int TenantId { get; set; }

        /// <summary>FK — the hire this check-in is for.</summary>
        public virtual Guid HireId { get; set; }

        /// <summary>Navigation to hire.</summary>
        public virtual Hire Hire { get; set; }

        /// <summary>FK — the associated journey.</summary>
        public virtual Guid JourneyId { get; set; }

        /// <summary>Navigation to journey.</summary>
        public virtual Journey Journey { get; set; }

        /// <summary>Milestone period at which this check-in is scheduled.</summary>
        [ReferenceList("JourneyPoint", "WellnessCheckInPeriods")]
        public virtual WellnessCheckInPeriod Period { get; set; }

        /// <summary>Current completion status of the check-in.</summary>
        [ReferenceList("JourneyPoint", "WellnessCheckInStatuses")]
        public virtual WellnessCheckInStatus Status { get; set; }

        /// <summary>Computed due date (Hire.StartDate + period offset days).</summary>
        public virtual DateTime ScheduledDate { get; set; }

        /// <summary>UTC time the hire submitted all answers.</summary>
        public virtual DateTime? SubmittedAt { get; set; }

        /// <summary>
        /// AI-generated summary of the hire's responses for Facilitator review.
        /// Generated by Groq on submission. Null until the check-in is submitted.
        /// </summary>
        [StringLength(2000)]
        public virtual string InsightSummary { get; set; }

        /// <summary>AI-generated questions with the hire's answers.</summary>
        public virtual ICollection<WellnessQuestion> Questions { get; set; }
    }
}
